### ISSUE TITLE
ModuleNotFoundError: No module named 'logger'

### ISSUE THREAD

**Issue by EnriqueSanchezdelVillar** [decalage2/ViperMonkey#102]
**Describe the bug**
I have installed _vipermonkey_ in my Parrot OS using `sudo -H pip install -U https://github.com/decalage2/ViperMonkey/archive/master.zip`

When I run (vmonkey) it I have the following error:
**Screenshots**
![WhatsApp Image 2020-11-16 at 08 17 37](https://user-images.githubusercontent.com/39306637/99223358-a6d5fa80-27e4-11eb-8df8-33f1d3e6351c.jpeg)

Could someone please help me with this? Is it enough information?

Thank you for your attention.
**Desktop (please complete the following information):**
 - OS: Parrot Os latest version

**Comment by decalage2** [comment]
Indeed it looks like a bug, it should be `from vipermonkey.core.logger import log` I think.

**Comment by valentinor78** [comment]
Hi,
I have the same problem in my Slackware OS. I tried to manually import the "core.logger" library (logger.py), but the result is below
`
Python 3.7.3 (default, May 27 2019, 18:06:09) 
[GCC 5.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import core.logger
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/[my path]/ViperMonkey/build/lib/vipermonkey/core/__init__.py", line 102, in <module>
    from logger import log
ModuleNotFoundError: No module named 'logger'
`

**Comment by valentinor78** [comment]
Hi,
I have the same problem in my Slackware OS. I tried to manually import the "core.logger" library (logger.py), but the result is below
`Python 3.7.3 (default, May 27 2019, 18:06:09) 
[GCC 5.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
> > > import core.logger
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/[my path]/ViperMonkey/build/lib/vipermonkey/core/__init__.py", line 102, in <module>
    from logger import log
ModuleNotFoundError: No module named 'logger'`

**Comment by valentinor78** [comment]
Hi,
I have the same problem in my Slackware OS. I tried to manually import the "core.logger" library (logger.py), but the result is below
`Python 3.7.3 (default, May 27 2019, 18:06:09) 
[GCC 5.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
  >  >  >  import core.logger
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/[my path]/ViperMonkey/build/lib/vipermonkey/core/__init__.py", line 102, in <module>
    from logger import log
ModuleNotFoundError: No module named 'logger'`

**Comment by valentinor78** [comment]
Hi,
I have the same problem in my Slackware OS. I tried to manually import the "core.logger" library (logger.py), but the result is below:
![image](https://user-images.githubusercontent.com/11964989/109400222-bd453380-7947-11eb-9147-49754dc73af4.png)

**Comment by decalage2** [comment]
In fact I just noticed that you are running vipermonkey with Python 3: this is not supported yet. Please try it with Python 2 or PyPy 2.

**Comment by ElTarget** [comment]
Hello, a few days ago, I started to build vipermonkey in my python2.7 environment, but the error during regex installation was displayed, "x86_64 Linux GNU GCC"。
I checked the regex module and found that python2 is no longer supported.
![image](https://user-images.githubusercontent.com/41426791/170899694-c2d4d75e-e1b1-4697-9864-fb0cce001aa0.png)

**Comment by ElTarget** [comment]
> 事实上，我刚刚注意到你正在运行Python 3的vipermonkey：这还不受支持。请尝试使用Python 2或PyPy 2。

Now I build it in the python3 environment, and it also shows the logger problem

**Comment by WHOLETTHEDOG-OUT** [comment]
> Hello, a few days ago, I started to build vipermonkey in my python2.7 environment, but the error during regex installation was displayed, "x86_64 Linux GNU GCC"。 I checked the regex module and found that python2 is no longer supported. ![image](https://user-images.githubusercontent.com/41426791/170899694-c2d4d75e-e1b1-4697-9864-fb0cce001aa0.png)

Meeting the same problem

**Comment by ElTarget** [comment]
Hello, I have directly done the migration of the Python version. Developed and used based on Python3.

**Comment by WHOLETTHEDOG-OUT** [comment]
> Hello, I have directly done the migration of the Python version. Developed and used based on Python3.

got it.
