### ISSUE TITLE
Fails to run from $PATH

### ISSUE THREAD

**Issue by scherma** [decalage2/ViperMonkey#17]
aphrodite@cleopatra:~$ vmonkey.py /var/cache/mail/F43942_7777204.docm
Traceback (most recent call last):
  File "/usr/local/bin/vmonkey.py", line 4, in <module>
    __import__('pkg_resources').run_script('vipermonkey==0.02', 'vmonkey.py')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 534, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1445, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/vipermonkey-0.02-py2.7.egg/EGG-INFO/scripts/vmonkey.py", line 95, in <module>

ImportError: No module named core

I can run it from my clone of the git repository, but the setup.py results seem to be borked. Version info:
3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-2+deb8u3 (2016-07-02) x86_64 GNU/Linux
Python3: 3.4.2, Python2: 2.7.9 (default)

**Comment by decalage2** [comment]
@scherma, could you please test the new version I just commited, and tell me if the issue is fixed for you?

**Comment by scherma** [comment]
Finished processing dependencies for vipermonkey==0.04
aphrodite@cleopatra:/usr/local/unsafehex/vipermonkey/ViperMonkey$ vmonkey.py /var/cache/mail/F43942_7777204.docm
Traceback (most recent call last):
  File "/usr/local/bin/vmonkey.py", line 4, in <module>
    __import__('pkg_resources').run_script('vipermonkey==0.04', 'vmonkey.py')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 534, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1438, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/vipermonkey-0.04-py2.7.egg/EGG-INFO/scripts/vmonkey.py", line 99, in <module>
    from core import *
ImportError: No module named core

Afraid not :(

**Comment by decalage2** [comment]
OK, indeed there seems to be an issue with the setup script. I'll look into it.

**Comment by decalage2** [comment]
@scherma, I have updated the setup script so that pip can create entry points instead of scripts.

If you run `pip install -U -e .` from the directory where setup.py is, it should automatically create entry points `vmonkey` and `vbashell` that you can run from anywhere. (no .py extension)

You may also directly run `pip install -U https://github.com/decalage2/ViperMonkey/archive/master.zip` to download and install in one go.

Please tell me if that new version works better.

**Comment by scherma** [comment]
Success! Wish I could help on the VBA parsing issues but my python-fu clearly has some catching up to do to reach your level :)
