### ISSUE TITLE
ImportError: No module named codes

### ISSUE THREAD

**Issue by hernanfila** [decalage2/ViperMonkey#43]
Hello, 
I have followed the same steps as https://github.com/decalage2/ViperMonkey/issues/40, but I have next error:
```
Traceback (most recent call last):
  File ".\vmonkey.py", line 103, in <module>
    from oletools.olevba import VBA_Parser, filter_vba
  File "C:\Users\xxx\Desktop\tools\pythonSW\PythonOld\lib\site-packages\oletools\olevba.py", line 300, in <module>
    from oletools import rtfobj
  File "C:\Users\xxx\Desktop\tools\pythonSW\PythonOld\lib\site-packages\oletools\rtfobj.py", line 121, in <module>
    from oletools.thirdparty.tablestream import tablestream
  File "C:\Users\xxx\Desktop\tools\pythonSW\PythonOld\lib\site-packages\oletools\thirdparty\tablestream\tablestream.py", line 82, in <module>
    import colorclass
  File "C:\Users\xxx\Desktop\tools\pythonSW\PythonOld\lib\site-packages\oletools\thirdparty\colorclass\__init__.py", line 11, in <module>
    from colorclass.codes import list_tags  # noqa
ImportError: No module named codes
```

**Expected behavior**
usage of vmonkey

**Desktop (please complete the following information):**
 - OS: Windows 10 

Thank you

**Comment by decalage2** [comment]
I think there's an issue in the documentation. I will also need to fix oletools to remove colorclass.
