### ISSUE TITLE
TypeError: 'str' object is not callable

### ISSUE THREAD

**Issue by Nametag18** [decalage2/ViperMonkey#98]
Receiving the following error:

-------------------------------------------------------------------------------
PARSING VBA CODE:
INFO     parsed Function ['SAOzzy'] ([ByRef ['FRcJIk'], ByRef ['TcSfEJA']]): 20 statement(s)
INFO     parsed Function ['CrjrHM'] ([ByRef ['IBAqabn'], ByRef ['fYjdNI']]): 9 statement(s)
INFO     parsed Function ['MKKHf'] ([ByRef ['WriPzI']]): 36 statement(s)
INFO     parsed Function ['ZcGtHb'] (): 13 statement(s)
INFO     parsed Function ['fppyj'] ([ByRef ['YLMiAh']]): 46 statement(s)
INFO     parsed Function ['QskdrM'] ([ByRef ['bovEyqN']]): 7 statement(s)
INFO     parsed Loose Lines Block: ([['On', 'Error', 'Resume', 'Next'] ...): 120 statement(s)
Traceback (most recent call last):
  File "vmonkey.py", line 1108, in _process_file
    vm.add_compiled_module(m)
  File "/home/nametag/Downloads/ViperMonkey-master/vipermonkey/core/__init__.py", line 250, in add_compiled_module
    self.globals[name.lower()] = _function
TypeError: 'str' object is not callable
ERROR    'str' object is not callable

Run on Python 2.7.17 - Ubuntu 18.04.4 LTS

FILE: script.vbs
INFO     Starting emulation...
INFO     Emulating a VBScript file.
INFO     Reading document metadata...
WARNING  Reading in metadata failed. Trying fallback. not an OLE2 structured storage file
ERROR    Cannot read metadata with exiftool. [Errno 2] No such file or directory
WARNING  The file is not an Office file. Not extracting sheets with LibreOffice.
ERROR    Reading in file as Excel with xlrd failed. Unsupported format, or corrupt file: Expected BOF record; found '\nOn Erro'
INFO     Saving dropped analysis artifacts in ./script.vbs_artifacts/
INFO     Parsing VB...

**Comment by alone-as-a-god** [comment]
Was this ever solved? Having a very similar issue

**Comment by BerryBest** [comment]
Hi, I have the same problem on street obj not callable. Anyone has idea how to solve this.
